version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/carlpett/stream_exporter
    steps:
      - checkout
      - run:
          name: Build
          command: |
            make promu
            git describe --always --tags | sed -r 's/^v//' | tee VERSION
            promu crossbuild
      - store_artifacts:
          path: .build
  docker-latest:
    docker:
      - image: circleci/golang:1.11
    steps:
      - run:
          name: Trigger Docker Hub automated build
          command: |
            curl -X POST -H "Content-Type: application/json" \
              --data "{\"docker_tag\": \"latest\"}" \
              https://registry.hub.docker.com/u/carlpett/stream_exporter/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/carlpett/stream_exporter
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Download github-release tool
          command: |
            curl -sL 'https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2' | \
              tar xjf - --strip-components 3 -C /go/bin
      - run:
          name: Create release
          commands: |
            make promu
            git describe --always --tags | sed -r 's/^v//' | tee VERSION
            promu crossbuild tarballs
            promu checksum .tarballs
            promu release .tarballs
      - run:
          name: Trigger Docker Hub automated build
          command: |
            curl -X POST -H "Content-Type: application/json" \
              --data "{\"source_type\": \"Tag\", \"source_name\": \"$CIRCLE_TAG\"}" \
              https://registry.hub.docker.com/u/carlpett/stream_exporter/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
      - store_artifacts:
          path: .build

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - docker-latest:
          filters:
            branches:
              only: master
          requires:
            - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
